apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-cache: "true"
    nginx.ingress.kubernetes.io/cache-generation: "1"  #
spec:
  rules:
  - http:
      paths:
      - path: / #anything starts with testpath forwards to test-service
        pathType: Prefix #because of this type
        backend:
          service:
            name: test-service
            port:
              number: 80
