apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: new-redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-redis
spec:
  selector:
    matchLabels:
      app: new-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: new-redis
    spec:
      containers:
      - name: new-redis
        image: redis:6
        ports:
        - containerPort: 6379
          name: "redis-port"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  selector:
    matchLabels:
      app: assignment
  replicas: 1
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: vinsdocker/k8s-deploy-assignment
        ports:
        - containerPort: 8080
          name: "app-port"
        env:
        - name: "spring.redis.host"
          value: "test-service" 
        - name: "spring.redis.port"
          value: "6379"
